spring:
  redis:
    database: 0
    host: 192.168.15.128
    port: 6379
    password: password
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        max-wait: -1ms
        min-idle: 0